### ISSUE TITLE
can only run make_zip with nodes

### ISSUE THREAD

**Issue by xross** [xross/tools_xpd2#9]
Traceback (most recent call last):
  File "../tools_xpd/xpd.py", line 2534, in <module>
    if command_fn(repo__, options, args):
  File "../tools_xpd/xpd.py", line 797, in xpd_make_zip
    insert_doc(repo.name, os.path.join(repo.path, docdir), f, is_xmos_repo=repo.is_xmos_repo(),
  File "../tools_xpd/xpd.py", line 1198, in insert_doc
    import_xdoc()
NameError: name 'import_xdoc' is not defined
(venv)

**Comment by xross** [comment]
This has now been somewhat hacked to work.. (doesn't actually build readme's etc)
